### ISSUE TITLE
doesn't work after install

### ISSUE THREAD

**Issue by saulemprendedor** [JS-banana/vite-vue3-ts#1]
doesn't work after install

 npm run dev

> vite-vue3-ts@0.0.0 dev /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts
> vite

failed to load config from /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts
error when starting dev server:
Error: Cannot find module 'unplugin-vue-components/resolvers'
Require stack:
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/cli.js
- /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts:114:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61911:20)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfigFromBundledFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61919:17)
    at loadConfigFromFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61838:32)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async resolveConfig (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61365:28)
    at async createServer (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59772:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vite-vue3-ts@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vite-vue3-ts@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/saulemprendedor/.npm/_logs/2022-05-03T03_12_42_852Z-debug.log

**Comment by JS-banana** [comment]
> doesn't work after install
> 
> npm run dev
> 
> > vite-vue3-ts@0.0.0 dev /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts
> > vite
> 
> failed to load config from /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts error when starting dev server: Error: Cannot find module 'unplugin-vue-components/resolvers' Require stack:
> 
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/cli.js
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/bin/vite.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
>   at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>   at Module.require (internal/modules/cjs/loader.js:848:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts:114:24)
>   at Module._compile (internal/modules/cjs/loader.js:955:30)
>   at Object.require.extensions. [as .ts] (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61911:20)
>   at Module.load (internal/modules/cjs/loader.js:811:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>   at Module.require (internal/modules/cjs/loader.js:848:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at loadConfigFromBundledFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61919:17)
>   at loadConfigFromFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61838:32)
>   at processTicksAndRejections (internal/process/task_queues.js:94:5)
>   at async resolveConfig (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61365:28)
>   at async createServer (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59772:20)
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! vite-vue3-ts@0.0.0 dev: `vite`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the vite-vue3-ts@0.0.0 dev script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /Users/saulemprendedor/.npm/_logs/2022-05-03T03_12_42_852Z-debug.log

Hi, according to your project log, it looks like the `unplugin-vue-components` dependency is not installed correctly, please install it again to make sure

**Comment by JS-banana** [comment]
> doesn't work after install
> 
> npm run dev
> 
> > vite-vue3-ts@0.0.0 dev /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts
> > vite
> 
> failed to load config from /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts error when starting dev server: Error: Cannot find module 'unplugin-vue-components/resolvers' Require stack:
> 
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/cli.js
> * /Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/bin/vite.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
>   at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>   at Module.require (internal/modules/cjs/loader.js:848:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/vite.config.ts:114:24)
>   at Module._compile (internal/modules/cjs/loader.js:955:30)
>   at Object.require.extensions. [as .ts] (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61911:20)
>   at Module.load (internal/modules/cjs/loader.js:811:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>   at Module.require (internal/modules/cjs/loader.js:848:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at loadConfigFromBundledFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61919:17)
>   at loadConfigFromFile (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61838:32)
>   at processTicksAndRejections (internal/process/task_queues.js:94:5)
>   at async resolveConfig (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:61365:28)
>   at async createServer (/Users/saulemprendedor/Documents/cleteci/vite-vue3-ts/node_modules/vite/dist/node/chunks/dep-88bd5805.js:59772:20)
>   npm ERR! code ELIFECYCLE
>   npm ERR! errno 1
>   npm ERR! vite-vue3-ts@0.0.0 dev: `vite`
>   npm ERR! Exit status 1
>   npm ERR!
>   npm ERR! Failed at the vite-vue3-ts@0.0.0 dev script.
>   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /Users/saulemprendedor/.npm/_logs/2022-05-03T03_12_42_852Z-debug.log

Hi, according to your project log, it looks like the unplugin-vue-components dependency is not installed correctly, please install it again to make sure

"unplugin-vue-components": "^0.17.2"
https://www.npmjs.com/package/unplugin-vue-components

```js
import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers';
import Components from 'unplugin-vue-components/vite';
```

**Comment by JS-banana** [comment]
This doesn't seem to be related to the project itself, so we recommend that you try using the pnpm package management tool, or test it with a yarn installation

https://pnpm.io/
https://yarnpkg.com/

![image](https://user-images.githubusercontent.com/42017491/167244195-a1cc4859-40d1-4911-b56b-93b48193e16f.png)
