### ISSUE TITLE
阅读过程中碰到的问题

### ISSUE THREAD

**Issue by Qishierhao** [JS-banana/vite-vue3-ts#2]
1、当3000端口被占用时，项目仍能启动在3000端口，暂时无法断定是否为vite的问题
2、login界面输入错误账号密码时，界面刷新，看不清message
3、http.ts :74中，config:AxiosRequestConfig将不能到达:75 if (typeof config === 'string') {，建议修改为config: AxiosRequestConfig | string

**Comment by JS-banana** [comment]
你好，谢谢反馈，针对你的问题，我进行了测试和验证：
1. 目前vite是有端口检测机制的（如果端口已经被使用，Vite 会自动尝试下一个可用的端口），就你的问题，我推测应该是已存在的3000端口的项目的监听端口方式有所不同导致vite无法正确检测导致（这有一篇类似的文章：https://jishuin.proginn.com/p/763bfbd59b28）
2. 针对这个问题，目前我的这个项目是使用了mock做了数据模拟，就登录逻辑而言应该是OK的（成功=>跳转首页，失败=>错误提示），具体逻辑走向可以结合实际调整。所以，你可以结合自身项目的使用场景进行调整。
3. 采纳，类型声明主要用于TypeScript类型推断（并不影响最终逻辑）
