### ISSUE TITLE
打包报错，这个怎么解决？

### ISSUE THREAD

**Issue by zhangbowy** [JS-banana/vite-vue3-ts#4]
![image](https://user-images.githubusercontent.com/33514252/178954883-23daab1c-2fe3-4077-8d14-0a357d80ce5f.png)

**Comment by JS-banana** [comment]
运行环境贴一下，node版本要大于14.x

**Comment by zhangbowy** [comment]
zhangbo@zhangbodeMacBook-Pro asset-web-pc % node -v
v14.18.1

**Comment by JS-banana** [comment]
确定开启了在css中对js的支持：

```js
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  }
```

**Comment by JS-banana** [comment]
> ![image](https://user-images.githubusercontent.com/33514252/178954883-23daab1c-2fe3-4077-8d14-0a357d80ce5f.png)

请确定开启了在css中对js的支持：

```js
  css: {
    preprocessorOptions: {
      less: {
        javascriptEnabled: true,
      },
    },
  }
```
