### ISSUE TITLE
pnpm install 的时候出现问题了

### ISSUE THREAD

**Issue by q3556499** [JS-banana/vite-vue3-ts#8]
![image](https://user-images.githubusercontent.com/54619424/182188433-1b9ed8cc-7324-4e32-99ef-6a20e0f4f36f.png)
我在pnpm的时候，显示这个错误我不知道怎么解决，希望你能帮助我一下

**Comment by JS-banana** [comment]
> ![image](https://user-images.githubusercontent.com/54619424/182188433-1b9ed8cc-7324-4e32-99ef-6a20e0f4f36f.png) 我在pnpm的时候，显示这个错误我不知道怎么解决，希望你能帮助我一下

1. 查看下你的网络和代理，错误显示是这个源没有对应资源，建议更换一下源
2. 还不行你可以尝试下使用yarn
3. 可以使用 nrm工具进行源管理
