### ISSUE TITLE
项目启动运行，要等待很久才会出来，有办法解决吗

### ISSUE THREAD

**Issue by wj-kyrie** [JS-banana/vite-vue3-ts#9]

**Comment by AngleSay** [comment]
同样的问题，启动很慢，启动之后凳面等待也是很慢，是使用缓存还是什么导致的呢？

**Comment by JS-banana** [comment]
😹😹😹
1. 第一，首次加载时，还没有缓存，消耗的时间会明显高出很多
2. 其次，这是因为 vite 机制的原因，要加载很多依赖文件，用控制台查看可以发现基本都会加载上百个文件
3. 虽然是本地加载，但是由于 chrome 的 http1.1 有加载并发限制，chrome 只允许 6 个同时并发，当我们在 vite 中配置了 server.https 为 ture 时，会自动使用 node 中的 http 2
4. 这个问题有一部分是因为 antd 的组件按需引用导致的，简单说就是首次启动项目时，vite在渲染组件时再不断的生成 antd 的组件依赖项（当然也有其他组件的依赖），可以选择提前将 antd 的组件进行依赖注册

参考链接：
1. [官方 Persistent Cache](https://github.com/vitejs/vite/issues/1309)
2. [Vite 解决项目刷新慢问题（请求量过大）](https://carljin.com/vite-resolve-request-files-a-ton.html)
3. [本地run启动, 都会等好久才会显示登录页面](https://github.com/vbenjs/vue-vben-admin/issues/1762)
